### PR TITLE
request body was not being used in hash

### PR DESCRIPTION
**Pull request by nata7che**
This is a fix for using the request body in the hash.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by nata7che** [comment]
DONE :)

**Comment by nata7che** [comment]
any idea how to make the Travis CI test pass?

**Comment by nata7che** [comment]
any chance to get a review and some help on the Travis CI issue?

**Comment by jeremyruppel** [comment]
First off, sorry for totally missing this PR for so long! We've been a little busy over at Flickr these days 😁 

So the travis issue looks like a lint issue where it's simply asking for a line between the var declaration on L22 and L23, so that should be easy enough to take care of and get the build moving again.

That said, it seems like this patch fails our current tests. They're already accounting for the request body being added to the hash (in the stream version it's written implicitly when piped, and in the sync version it's being written to the hash by hand directly after `updateHash`). If you're seeing unexpected behavior, could you provide a test that demonstrates what you're seeing? Thanks!

**Comment by jeremyruppel** [comment]
@nata7che please feel free to reopen this PR if you're still seeing unexpected behavior. Thanks!

**Pull request closed without merging**
